// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remoteproc.proto

package remoteproc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cursor struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e8e358145d4354, []int{0}
}

func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (m *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(m, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

func (m *Cursor) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Cursor) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Rect struct {
	Top                  int32    `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
	Left                 int32    `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Bottom               int32    `protobuf:"varint,3,opt,name=bottom,proto3" json:"bottom,omitempty"`
	Right                int32    `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rect) Reset()         { *m = Rect{} }
func (m *Rect) String() string { return proto.CompactTextString(m) }
func (*Rect) ProtoMessage()    {}
func (*Rect) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e8e358145d4354, []int{1}
}

func (m *Rect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rect.Unmarshal(m, b)
}
func (m *Rect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rect.Marshal(b, m, deterministic)
}
func (m *Rect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rect.Merge(m, src)
}
func (m *Rect) XXX_Size() int {
	return xxx_messageInfo_Rect.Size(m)
}
func (m *Rect) XXX_DiscardUnknown() {
	xxx_messageInfo_Rect.DiscardUnknown(m)
}

var xxx_messageInfo_Rect proto.InternalMessageInfo

func (m *Rect) GetTop() int32 {
	if m != nil {
		return m.Top
	}
	return 0
}

func (m *Rect) GetLeft() int32 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *Rect) GetBottom() int32 {
	if m != nil {
		return m.Bottom
	}
	return 0
}

func (m *Rect) GetRight() int32 {
	if m != nil {
		return m.Right
	}
	return 0
}

type Resolution struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resolution) Reset()         { *m = Resolution{} }
func (m *Resolution) String() string { return proto.CompactTextString(m) }
func (*Resolution) ProtoMessage()    {}
func (*Resolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e8e358145d4354, []int{2}
}

func (m *Resolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resolution.Unmarshal(m, b)
}
func (m *Resolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resolution.Marshal(b, m, deterministic)
}
func (m *Resolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resolution.Merge(m, src)
}
func (m *Resolution) XXX_Size() int {
	return xxx_messageInfo_Resolution.Size(m)
}
func (m *Resolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Resolution.DiscardUnknown(m)
}

var xxx_messageInfo_Resolution proto.InternalMessageInfo

func (m *Resolution) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Resolution) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type WindowInfo struct {
	ProcName             string      `protobuf:"bytes,1,opt,name=procName,proto3" json:"procName,omitempty"`
	ClientRect           *Rect       `protobuf:"bytes,2,opt,name=clientRect,proto3" json:"clientRect,omitempty"`
	MonitorResolution    *Resolution `protobuf:"bytes,3,opt,name=monitorResolution,proto3" json:"monitorResolution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WindowInfo) Reset()         { *m = WindowInfo{} }
func (m *WindowInfo) String() string { return proto.CompactTextString(m) }
func (*WindowInfo) ProtoMessage()    {}
func (*WindowInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e8e358145d4354, []int{3}
}

func (m *WindowInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowInfo.Unmarshal(m, b)
}
func (m *WindowInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowInfo.Marshal(b, m, deterministic)
}
func (m *WindowInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowInfo.Merge(m, src)
}
func (m *WindowInfo) XXX_Size() int {
	return xxx_messageInfo_WindowInfo.Size(m)
}
func (m *WindowInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WindowInfo proto.InternalMessageInfo

func (m *WindowInfo) GetProcName() string {
	if m != nil {
		return m.ProcName
	}
	return ""
}

func (m *WindowInfo) GetClientRect() *Rect {
	if m != nil {
		return m.ClientRect
	}
	return nil
}

func (m *WindowInfo) GetMonitorResolution() *Resolution {
	if m != nil {
		return m.MonitorResolution
	}
	return nil
}

func init() {
	proto.RegisterType((*Cursor)(nil), "remoteproc.Cursor")
	proto.RegisterType((*Rect)(nil), "remoteproc.Rect")
	proto.RegisterType((*Resolution)(nil), "remoteproc.Resolution")
	proto.RegisterType((*WindowInfo)(nil), "remoteproc.WindowInfo")
}

func init() { proto.RegisterFile("remoteproc.proto", fileDescriptor_28e8e358145d4354) }

var fileDescriptor_28e8e358145d4354 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xe5, 0xd7, 0x34, 0xe8, 0x54, 0x21, 0x0e, 0x52, 0x42, 0x4f, 0xb2, 0x78, 0xf0, 0x54,
	0x24, 0xde, 0x04, 0x4f, 0x0a, 0x22, 0x82, 0xc8, 0x5e, 0x04, 0x6f, 0x36, 0xdd, 0x9a, 0x85, 0x64,
	0x27, 0x6c, 0xa7, 0xb4, 0xfd, 0x36, 0x7e, 0x54, 0xd9, 0x3f, 0x9a, 0x14, 0x6f, 0xfb, 0x5e, 0xde,
	0x7b, 0x33, 0x2f, 0x03, 0xb9, 0x55, 0x2d, 0xb1, 0xea, 0x2c, 0x55, 0xf3, 0xce, 0x12, 0x13, 0x42,
	0xcf, 0x88, 0x4b, 0xc8, 0xee, 0x37, 0x76, 0x4d, 0x16, 0x4f, 0x20, 0xd9, 0x15, 0xc9, 0x45, 0x72,
	0x35, 0x96, 0xc9, 0xce, 0xa1, 0x7d, 0xf1, 0x3f, 0xa0, 0xbd, 0x78, 0x87, 0x54, 0xaa, 0x8a, 0x31,
	0x87, 0x11, 0x53, 0x17, 0x55, 0xee, 0x89, 0x08, 0x69, 0xa3, 0x56, 0x1c, 0xa5, 0xfe, 0x8d, 0x53,
	0xc8, 0x16, 0xc4, 0x4c, 0x6d, 0x31, 0xf2, 0x6c, 0x44, 0x78, 0x0e, 0x63, 0xab, 0x3f, 0x6b, 0x2e,
	0x52, 0x4f, 0x07, 0x20, 0x6e, 0x01, 0xa4, 0x5a, 0x53, 0xb3, 0x61, 0x4d, 0xc6, 0x69, 0xb6, 0x7a,
	0xc9, 0x75, 0x9c, 0x11, 0x80, 0x4b, 0xac, 0x95, 0xb7, 0x86, 0x39, 0x11, 0x89, 0xaf, 0x04, 0xe0,
	0x4d, 0x9b, 0x25, 0x6d, 0x9f, 0xcc, 0x8a, 0x70, 0x06, 0x47, 0xae, 0xd4, 0xcb, 0x47, 0xab, 0xbc,
	0xff, 0x58, 0xfe, 0x62, 0xbc, 0x06, 0xa8, 0x1a, 0xad, 0x0c, 0xbb, 0x22, 0x3e, 0x66, 0x52, 0xe6,
	0xf3, 0xc1, 0xbf, 0x71, 0xbc, 0x1c, 0x68, 0xf0, 0x01, 0xce, 0x5a, 0x32, 0x9a, 0xc9, 0xf6, 0xfb,
	0xf9, 0x46, 0x93, 0x72, 0x7a, 0x68, 0xfc, 0xf9, 0x2a, 0xff, 0x1a, 0xca, 0x67, 0x57, 0xcf, 0x69,
	0x5f, 0x2d, 0x55, 0x78, 0x07, 0xa7, 0x8f, 0x8a, 0x07, 0x2b, 0xe3, 0x30, 0x29, 0x5c, 0x62, 0x76,
	0x90, 0xde, 0x6b, 0xc5, 0xbf, 0x45, 0xe6, 0x0f, 0x78, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x51,
	0xc6, 0x5a, 0x0b, 0xd4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteProcClient is the client API for RemoteProc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteProcClient interface {
	GetWindowInfo(ctx context.Context, in *Cursor, opts ...grpc.CallOption) (*WindowInfo, error)
}

type remoteProcClient struct {
	cc *grpc.ClientConn
}

func NewRemoteProcClient(cc *grpc.ClientConn) RemoteProcClient {
	return &remoteProcClient{cc}
}

func (c *remoteProcClient) GetWindowInfo(ctx context.Context, in *Cursor, opts ...grpc.CallOption) (*WindowInfo, error) {
	out := new(WindowInfo)
	err := c.cc.Invoke(ctx, "/remoteproc.RemoteProc/GetWindowInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteProcServer is the server API for RemoteProc service.
type RemoteProcServer interface {
	GetWindowInfo(context.Context, *Cursor) (*WindowInfo, error)
}

func RegisterRemoteProcServer(s *grpc.Server, srv RemoteProcServer) {
	s.RegisterService(&_RemoteProc_serviceDesc, srv)
}

func _RemoteProc_GetWindowInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cursor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteProcServer).GetWindowInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remoteproc.RemoteProc/GetWindowInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteProcServer).GetWindowInfo(ctx, req.(*Cursor))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteProc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remoteproc.RemoteProc",
	HandlerType: (*RemoteProcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWindowInfo",
			Handler:    _RemoteProc_GetWindowInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remoteproc.proto",
}
